// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Del(arg1) {
  return window['go']['main']['App']['Del'](arg1);
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function PingAll() {
  return window['go']['main']['App']['PingAll']();
}

export function SetPeer(arg1, arg2) {
  return window['go']['main']['App']['SetPeer'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
